service: serverless-graphql-api-demo

frameworkVersion: ">=1.26.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules: true


functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
  graphiql:
    handler: handler.graphiqlHandler
    events:
    - http:
        path: graphiql
        method: get
        cors: true